# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1us9wlNzvP_KXKJGj0BqiDrziovXsSTG2
"""

import streamlit as st
import tensorflow as tf
import numpy as np
import librosa
import soundfile as sf
import tempfile

st.title("🎵 Audio Emotion Detection")

# -------------------
# Load the model
# -------------------
@st.cache_resource  # caches model for faster reloads
def load_model():
    model = tf.keras.models.load_model("mymodel_v2")  # SavedModel folder
    return model

model = load_model()

# -------------------
# Upload audio file
# -------------------
uploaded_file = st.file_uploader("Upload a WAV file", type=["wav", "flac", "ogg"])
if uploaded_file is not None:
    # Save temporary file
    with tempfile.NamedTemporaryFile(delete=False) as tmp:
        tmp.write(uploaded_file.read())
        temp_path = tmp.name

    # Load audio
    y, sr = librosa.load(temp_path, sr=None)

    # Example feature extraction: MFCCs
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
    mfccs = mfccs.T  # shape: (timesteps, features)
    mfccs = np.expand_dims(mfccs, axis=0)  # add batch dimension

    # Predict
    predictions = model.predict(mfccs)
    predicted_class = np.argmax(predictions, axis=1)[0]

    # Example emotion labels (adjust to your dataset)
    emotion_labels = ["neutral", "happy", "sad", "angry", "fearful", "disgust", "surprised", "calm"]
    st.write(f"Predicted Emotion: **{emotion_labels[predicted_class]}**")

    # Show probabilities
    st.write("Probabilities:")
    st.write(dict(zip(emotion_labels, predictions[0])))