# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwVjNGjsCiy9ZdQzNB8JXZlmrUTvMwAl
"""

model.save("mymodel_v2")